### ISSUE TITLE
Doesn't run old migration

### ISSUE THREAD

**Issue by mxstbr** [vinicius0026/rethinkdb-migrate#22]
Say you have two people working on an app, both in a separate branch. (`branch-a` and `branch-b`) First the person on `branch-b` creates a migration to develop their feature, then the person on `branch-a`.

Now `branch-a` gets merged and the migration from that branch ran in production. Sometime later `branch-b` is merged, but the issue is that the `branch-b` migration doesn't run production, I assume because it's "older" than the last one that was ran from `branch-a`.

Any ideas how to fix this?

**Comment by lirantal** [comment]
For that reason and others I proposed #21 which got merged and you just need to make sure you use the latest npm version, then execute migrations with -i and it will apply all migrations regardless of their timestamp.
