### ISSUE TITLE
Can this module be used to migrate data from rethink to mongo/cassandra

### ISSUE THREAD

**Issue by prashathsenthil** [vinicius0026/rethinkdb-migrate#26]
Hi,

Came across this module and was wondering if it can be used to migrate the data residing in rethinkdb to either mongo or cassandra? The data volume is huge and looking for an elegant and performance effective way to migrate data.

**Comment by lirantal** [comment]
Hi @prashathsenthil,

Not really, it's not a db to db migration tool in that context.
This module handles database migrations in terms of tear-up, tear-down scripts for when you want to make incremental updates to your database schema/model, etc.

Goodluck!

**Comment by prashathsenthil** [comment]
@lirantal got you! Thanks for the quick turnaround!! Really appreciate it!!!
