### ISSUE TITLE
Impossible to migrate

### ISSUE THREAD

**Issue by S-Maxime** [vinicius0026/rethinkdb-migrate#30]
Good evening ! x)

I'm trying to migrate a table but i get this error

Do you have any idea how can i fix this please ?

Here my migration.js who contain my configuration... (i will rename this when that's going to work correctly ^^)

``
module.exports = {
    db: "qwirk",
    driver: "rethinkdb",
    pool: true,
    servers: [
        { host: "localhost", port: 28015 }
    ],
    ssl: false
}
``

exports.up = function (r, connection) {
  return Promise.all([
    r.tableCreate('users').run(connection)
  ])
}

exports.down = function (r, connection) {
  return Promise.all([
    r.tableDrop('users').run(connection)
  ])
}
![error_thinkdb](https://user-images.githubusercontent.com/16159090/37568529-87cc708c-2ad6-11e8-8df1-ecb7bdb7e660.png)

and i tried this : npm run migrate up -f config/migration.js

**Comment by lirantal** [comment]
@Ravaniss can you try to give it the actual config file for the migrations? meaning `config/migration.js` doesn't seem to be your config file which is `config.json` - which also has an issue its a json file not a javascript file.

**Comment by S-Maxime** [comment]
Hey, sorry, the file name is "migration.js"... Ive tried a lot than i wrote a little too fast ^^' who contain this : 

`module.exports = { db: "qwirk", driver: "rethinkdb", pool: true, servers: [ { host: "localhost", port: 28015 } ], ssl: false }`

I've updated my first post

**Comment by S-Maxime** [comment]
Hi, i don't really know why i get this damn error than i have "db" on my migrations.js ... Always locked with this error. :/

Someone have a solution about how can i fix this please ? ^^

**Comment by S-Maxime** [comment]
Well, i did it myself without any package... I close this issue...
