### ISSUE TITLE
Migration scripts handling errors

### ISSUE THREAD

**Issue by lirantal** [vinicius0026/rethinkdb-migrate#9]
Vinicius I'll open up with a big thanks for working out a newly maintained module for handling rethinkdb migrations.

I'm new to rethinkdb and want to bring up an issue - if a migration script attempts to create a database to ensure it exists then the promise is rejected obviously, but I suspect this happens because the rethinkdb-migrate tool itself triggers the db migration when populating the _migrations table.

I came up with the following work-around in my migration script:

```js
'use strict'

exports.up = function (r, connection) {
  return new Promise((resolve, reject) => {
    r.dbCreate('some_db_name').run()
      .then(() => resolve())
      .catch((e) => {
        if (e.message.indexOf('already exists') !== false) {
          resolve()
        } else {
          reject(e)
        }
      })
  })
}

exports.down = function (r, connection) {
  // must return a Promise!
}
```

I wanted to share and see if it's just me, a known concern or there's generally a better pattern for this.

**Comment by vinicius0026** [comment]
Hi Liran.

The migration script will check if the provided db exists, and if it doesn't exist, the db will be created (as per https://github.com/vinicius0026/rethinkdb-migrate/blob/master/lib/migrate.js#L109-L125)  before running any migration.

How are you running your migrations? Which driver are you using, rethinkdb or rethinkdbdash? I think your workaround might be masking some other errors.

Do you really need to create the db in the migration file? Do you do any special setup when creating the database that should be done on creation step? If you don't need this, you can rely on the tool to create the db for you.

**Comment by lirantal** [comment]
I don't think there's any masked errors here.
That snippet of code you shared is actually the exact reason for why my attempt to create the db yields an error, because the `rethinkdb-migrate` tool itself is trying to create the database first, then my migration attempts to do it.

So it seems that the guideline is that one doesn't need to explicitly create the database for which `rethinkdb-migrate` is configured to save _migrations for because the tool will attempt to do that on it's own. Is that about right?

BTW using rethinkdbdash.

**Comment by vinicius0026** [comment]
Well, that is the current behaviour, which is the same thing rethink-migrate (the lib on which this tool is based) did. It could be changed, if there is any reason for doing so.

I ran your code using both drivers, and with rethinkdb driver there was an error masked (no connection was passed to run method), but since you are using rethinkdbdash (with pools, I presume), this should not happen.

**Comment by lirantal** [comment]
Right.

So like I said, I don't mind closing this issue as long as creating the database for the migrations 'on the fly' is actually an expected method. Meaning, the guideline is that there should be no reason for anyone to run dbCreate() for the same database that rethinkdb-migration is configured to work with.

**Comment by vinicius0026** [comment]
Yes, that's the current expected behaviour. I'll make it clearer in the docs.
